# Generated by Django 3.2.5 on 2021-07-11 11:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customersapi', '0002_auto_20210711_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='Phone',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(code='nomatch', message='Invalid Phone Number Please Use Format 0xxxxxxxxxx', regex='/^(0)([0-9])\\s?([0-9]{3})\\s?([0-9]{2})\\s?([0-9]{2})$/')]),
        ),
    ]
