# Generated by Django 3.2.5 on 2021-07-11 11:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customersapi', '0003_alter_customers_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='Phone',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(code='nomatch', message='Invalid Phone Number Please Use Format 0xxxxxxxxxx', regex='/^(05)([0-9]{2})\\s?([0-9]{3})\\s?([0-9]{2})\\s?([0-9]{2})$/')]),
        ),
    ]
