# Generated by Django 3.2.5 on 2021-07-11 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customersapi', '0004_alter_customers_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='Phone',
            field=models.CharField(max_length=11),
        ),
    ]
